# Generated by generate_simulator_abi_bindings.py; do not edit.
# Candidate/shadow binding only. Importing this file does not activate V0.4.

PROFILE_ID = 'RTCORE_SIMULATOR_ABI_V04_FULL_TRACE_EFFECT_128B'
PROFILE_VERSION = '0.4.0'
LAYOUT_ID = 'RTCORE_HANDOFF_PROFILE_V04_FULL_TRACE_EFFECT_128B'
LAYOUT_VALUE = 0x00000003
LAYOUT_VERSION = 0x00000001
LANE_SLOT_BYTES = 128
WORD_COUNT = 32
SOURCE_INPUT_SHA256 = 'bef91023da5e0a801954a15d6cad17e6f9aeabef23b93a436db2d9276e8072b0'

FIELD_SPECS = {
    'context_address_low32': (0, 0, 32, 0xffffffff),
    'context_address_high32': (1, 0, 32, 0xffffffff),
    'traversable_reference_low32': (2, 0, 32, 0xffffffff),
    'traversable_reference_high32': (3, 0, 32, 0xffffffff),
    'world_ray_origin_x_fp32': (4, 0, 32, 0xffffffff),
    'world_ray_origin_y_fp32': (5, 0, 32, 0xffffffff),
    'world_ray_origin_z_fp32': (6, 0, 32, 0xffffffff),
    'ray_tmin_fp32': (7, 0, 32, 0xffffffff),
    'world_ray_direction_x_fp32': (8, 0, 32, 0xffffffff),
    'world_ray_direction_y_fp32': (9, 0, 32, 0xffffffff),
    'world_ray_direction_z_fp32': (10, 0, 32, 0xffffffff),
    'launch_ray_tmax_fp32': (11, 0, 32, 0xffffffff),
    'ray_flags': (12, 0, 32, 0xffffffff),
    'cull_mask': (13, 0, 8, 0x000000ff),
    'sbt_record_offset': (13, 8, 4, 0x00000f00),
    'sbt_record_stride': (13, 12, 4, 0x0000f000),
    'miss_index': (13, 16, 16, 0xffff0000),
    'instance_metadata_reference_low32': (14, 0, 32, 0xffffffff),
    'instance_metadata_reference_high32': (15, 0, 32, 0xffffffff),
    'instance_sbt_contribution': (16, 0, 32, 0xffffffff),
    'geometry_index': (17, 0, 32, 0xffffffff),
    'boundary_ray_tmax_fp32': (18, 0, 32, 0xffffffff),
    'primitive_index': (19, 0, 32, 0xffffffff),
    'instance_index': (20, 0, 32, 0xffffffff),
    'instance_custom_index': (21, 0, 32, 0xffffffff),
    'hit_kind': (22, 0, 8, 0x000000ff),
    'procedural_any_hit_eligible': (22, 8, 1, 0x00000100),
    'input_attribute_word_count': (23, 0, 8, 0x000000ff),
    'input_attribute_location': (23, 8, 8, 0x0000ff00),
    'input_attribute_format': (23, 16, 8, 0x00ff0000),
    'commit_retained_candidate': (24, 0, 1, 0x00000001),
    'accepted_reported_hit_valid': (24, 1, 1, 0x00000002),
    'terminate_search': (24, 2, 1, 0x00000004),
    'reported_t_fp32': (25, 0, 32, 0xffffffff),
    'reported_hit_kind': (26, 0, 8, 0x000000ff),
    'reported_attribute_word_count': (26, 8, 8, 0x0000ff00),
    'reported_attribute_format': (26, 16, 8, 0x00ff0000),
    'inline_attribute_word_0': (28, 0, 32, 0xffffffff),
    'inline_attribute_word_1': (29, 0, 32, 0xffffffff),
    'inline_attribute_word_2': (30, 0, 32, 0xffffffff),
    'inline_attribute_word_3': (31, 0, 32, 0xffffffff),
}
FIELD_PRODUCERS = {
    'context_address_low32': 'trace_launch_software',
    'context_address_high32': 'trace_launch_software',
    'traversable_reference_low32': 'trace_launch_software',
    'traversable_reference_high32': 'trace_launch_software',
    'world_ray_origin_x_fp32': 'trace_launch_software',
    'world_ray_origin_y_fp32': 'trace_launch_software',
    'world_ray_origin_z_fp32': 'trace_launch_software',
    'ray_tmin_fp32': 'trace_launch_software',
    'world_ray_direction_x_fp32': 'trace_launch_software',
    'world_ray_direction_y_fp32': 'trace_launch_software',
    'world_ray_direction_z_fp32': 'trace_launch_software',
    'launch_ray_tmax_fp32': 'trace_launch_software',
    'ray_flags': 'trace_launch_software',
    'cull_mask': 'trace_launch_software',
    'sbt_record_offset': 'trace_launch_software',
    'sbt_record_stride': 'trace_launch_software',
    'miss_index': 'trace_launch_software',
    'instance_metadata_reference_low32': 'rtcore',
    'instance_metadata_reference_high32': 'rtcore',
    'instance_sbt_contribution': 'rtcore',
    'geometry_index': 'rtcore',
    'boundary_ray_tmax_fp32': 'rtcore',
    'primitive_index': 'rtcore',
    'instance_index': 'rtcore',
    'instance_custom_index': 'rtcore',
    'hit_kind': 'rtcore',
    'procedural_any_hit_eligible': 'rtcore',
    'input_attribute_word_count': 'rtcore',
    'input_attribute_location': 'rtcore',
    'input_attribute_format': 'rtcore',
    'commit_retained_candidate': 'shader_software',
    'accepted_reported_hit_valid': 'shader_software',
    'terminate_search': 'shader_software',
    'reported_t_fp32': 'shader_software',
    'reported_hit_kind': 'shader_software',
    'reported_attribute_word_count': 'shader_software',
    'reported_attribute_format': 'shader_software',
    'inline_attribute_word_0': 'rtcore_or_shader_software_phase_selected',
    'inline_attribute_word_1': 'rtcore_or_shader_software_phase_selected',
    'inline_attribute_word_2': 'rtcore_or_shader_software_phase_selected',
    'inline_attribute_word_3': 'rtcore_or_shader_software_phase_selected',
}
RESERVED_MASKS = (0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0xfffffe00, 0xff000000, 0xfffffff8, 0x00000000, 0xff000000, 0xffffffff, 0x00000000, 0x00000000, 0x00000000, 0x00000000,)
COMPACT_RESULT_FIELD_SPECS = {
    'rt_return_reason': (0, 8, 0x000000ff),
    'completion_valid': (31, 1, 0x80000000),
}
COMPACT_RESULT_RESERVED_MASK = 0x7fffff00
RETURN_REASONS = {
    'NONE_OR_INVALID': 0x00,
    'MISS': 0x01,
    'CLOSEST_HIT_READY': 0x02,
    'ANY_HIT_REQUIRED': 0x03,
    'INTERSECTION_REQUIRED': 0x04,
    'TRACE_DONE_NO_SHADER': 0x05,
    'RESERVED_FAULT_NOT_PRODUCED': 0x06,
    'RESERVED_UNSUPPORTED_NOT_PRODUCED': 0x07,
}
LEGAL_TRAVERSAL_EFFECTS = {
    'ANY_HIT_REQUIRED': (0x0, 0x1, 0x5,),
    'INTERSECTION_REQUIRED': (0x0, 0x2, 0x6,),
}
CANONICAL_FIXTURE_ID = 'RTCORE_SIMULATOR_ABI_V04_CANONICAL_INTERSECTION_RETURN'
CANONICAL_FIXTURE_FIELDS = (
    ('context_address_low32', 0x55667788),
    ('context_address_high32', 0x11223344),
    ('traversable_reference_low32', 0x44332210),
    ('traversable_reference_high32', 0x88776655),
    ('world_ray_origin_x_fp32', 0x3f800000),
    ('world_ray_origin_y_fp32', 0xc0000000),
    ('world_ray_origin_z_fp32', 0x40600000),
    ('ray_tmin_fp32', 0x3e800000),
    ('world_ray_direction_x_fp32', 0x00000000),
    ('world_ray_direction_y_fp32', 0x3f800000),
    ('world_ray_direction_z_fp32', 0xbf800000),
    ('launch_ray_tmax_fp32', 0x42c80000),
    ('ray_flags', 0x0000a5a5),
    ('cull_mask', 0x0000007f),
    ('sbt_record_offset', 0x0000000a),
    ('sbt_record_stride', 0x00000005),
    ('miss_index', 0x00001234),
    ('instance_metadata_reference_low32', 0x89abcdef),
    ('instance_metadata_reference_high32', 0x01234567),
    ('instance_sbt_contribution', 0x10203040),
    ('geometry_index', 0x50607080),
    ('boundary_ray_tmax_fp32', 0x41400000),
    ('primitive_index', 0x0badc0de),
    ('instance_index', 0x13572468),
    ('instance_custom_index', 0x24681357),
    ('hit_kind', 0x00000000),
    ('procedural_any_hit_eligible', 0x00000001),
    ('input_attribute_word_count', 0x00000000),
    ('input_attribute_location', 0x00000000),
    ('input_attribute_format', 0x00000000),
    ('commit_retained_candidate', 0x00000000),
    ('accepted_reported_hit_valid', 0x00000001),
    ('terminate_search', 0x00000001),
    ('reported_t_fp32', 0x40e00000),
    ('reported_hit_kind', 0x0000002a),
    ('reported_attribute_word_count', 0x00000004),
    ('reported_attribute_format', 0x00000002),
    ('inline_attribute_word_0', 0xdeadbeef),
    ('inline_attribute_word_1', 0x01020304),
    ('inline_attribute_word_2', 0x55667788),
    ('inline_attribute_word_3', 0xa5a55a5a),
)
CANONICAL_FIXTURE_WORDS = (0x55667788, 0x11223344, 0x44332210, 0x88776655, 0x3f800000, 0xc0000000, 0x40600000, 0x3e800000, 0x00000000, 0x3f800000, 0xbf800000, 0x42c80000, 0x0000a5a5, 0x12345a7f, 0x89abcdef, 0x01234567, 0x10203040, 0x50607080, 0x41400000, 0x0badc0de, 0x13572468, 0x24681357, 0x00000100, 0x00000000, 0x00000006, 0x40e00000, 0x0002042a, 0x00000000, 0xdeadbeef, 0x01020304, 0x55667788, 0xa5a55a5a,)
CANONICAL_FIXTURE_BYTES_HEX = '887766554433221110223344556677880000803f000000c0000060400000803e000000000000803f000080bf0000c842a5a500007f5a3412efcdab8967452301403020108070605000004041dec0ad0b68245713571368240001000000000000060000000000e0402a04020000000000efbeadde04030201887766555a5aa5a5'
CANONICAL_FIXTURE_COMPACT_RESULT = 0x80000004
CANONICAL_FIXTURE_BOUNDARY = 'INTERSECTION_REQUIRED'


def insert_field(words, field_name, value):
    if field_name not in FIELD_SPECS:
        raise ValueError('unknown or reserved V0.4 field: %s' % field_name)
    word, lsb, width, mask = FIELD_SPECS[field_name]
    if not isinstance(value, int) or isinstance(value, bool) or value < 0 or value >= (1 << width):
        raise ValueError('%s does not fit %u bits' % (field_name, width))
    words[word] = (words[word] & ~mask) | ((value << lsb) & mask)


def extract_field(words, field_name):
    word, lsb, _width, mask = FIELD_SPECS[field_name]
    return (words[word] & mask) >> lsb


def pack_fields(values):
    words = [0] * WORD_COUNT
    for field_name, value in values.items():
        insert_field(words, field_name, value)
    validate_reserved_zero(words)
    return tuple(words)


def encode_words_le(words):
    if len(words) != WORD_COUNT:
        raise ValueError('V0.4 lane slot must have %u words' % WORD_COUNT)
    validate_reserved_zero(words)
    return b''.join(int(word).to_bytes(4, 'little') for word in words)


def decode_words_le(image):
    if len(image) != LANE_SLOT_BYTES:
        raise ValueError('V0.4 lane slot must have %u bytes' % LANE_SLOT_BYTES)
    words = tuple(int.from_bytes(image[offset:offset + 4], 'little')
                  for offset in range(0, len(image), 4))
    validate_reserved_zero(words)
    return words


def validate_reserved_zero(words):
    if len(words) != WORD_COUNT:
        raise ValueError('V0.4 lane slot must have %u words' % WORD_COUNT)
    for index, (word, reserved) in enumerate(zip(words, RESERVED_MASKS)):
        if not isinstance(word, int) or isinstance(word, bool) or word < 0 or word > 0xffffffff:
            raise ValueError('w%u is not a u32' % index)
        if word & reserved:
            raise ValueError('w%u sets reserved bits 0x%08x' % (index, word & reserved))


def pack_compact_result(reason_name, completion_valid):
    if reason_name not in RETURN_REASONS:
        raise ValueError('unknown V0.4 return reason: %s' % reason_name)
    if not isinstance(completion_valid, bool):
        raise ValueError('completion_valid must be bool')
    reason_lsb, _reason_width, reason_mask = COMPACT_RESULT_FIELD_SPECS['rt_return_reason']
    valid_lsb, _valid_width, valid_mask = COMPACT_RESULT_FIELD_SPECS['completion_valid']
    value = ((RETURN_REASONS[reason_name] << reason_lsb) & reason_mask)
    if completion_valid:
        value |= (1 << valid_lsb) & valid_mask
    if value & COMPACT_RESULT_RESERVED_MASK:
        raise ValueError('compact result sets reserved bits')
    return value


def validate_traversal_effect(boundary_name, effect):
    legal = LEGAL_TRAVERSAL_EFFECTS.get(boundary_name)
    if legal is None or effect not in legal:
        raise ValueError('illegal traversal effect 0x%x for %s' % (effect, boundary_name))
